name: BarrelOfCider

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    paths-ignore:
      - '.github/workflows/*'

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install valgrind
        run: sudo apt install valgrind
      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      - uses: actions/checkout@v3
      - name: make
        run: make
      - name: test of BankOfUsers
        run: ./BUtests
      - name: test of Logs
        run: ./LogsTests
      - name: test of DataBank
        run: ./DBtests
      - name: test of LexicalAnalysis
        run: ./LAtests
      - name: test of memory of Log
        run: valgrind --tool=memcheck --leak-check=full --undef-value-errors=no --error-exitcode=111 ./LogsTests
      - name: test of memory of BankOfUsers
        run: valgrind --tool=memcheck --leak-check=full --undef-value-errors=no --error-exitcode=111 ./BUtests
      - name: test of memory of DataBank
        run: valgrind --tool=memcheck --leak-check=full --undef-value-errors=no --error-exitcode=111 ./DBtests
      - name: test of memory of LexicalAnalysis
        run: valgrind --tool=memcheck --leak-check=full --undef-value-errors=no --error-exitcode=111 ./LAtests
      - name: make clean
        run: make clean